name: Test branch
on:
  push:
    branches-ignore:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.12.0'
      - run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
